### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by ghost** [x86y/beacon#6]
It's my assumption (certainly my first-hand experience) that this project will appeal as a first contact with BQN, so having to build and integrate it manually (with hiccups: #3, #5) will be a non-negligible hurdle. Indexing it in third-party package managers will have great effect.

Certainly, there's not much point even thinking about this unless dzaima/CBQN#110 is implemented first.

**Comment by x86y** [comment]
https://github.com/x86y/beacon/issues/5#issuecomment-2241105077
